### PR TITLE
feat(coverage) springfox.bean 100% coverage

### PR DESCRIPTION
**Pull request by carlosjgp**
Added tests for all the classes and methods for the package springfox.bean in the module Springfox Bean Validators

### CODE REVIEW

**Comment by jfiala** [comment]
@carlosjgp Thx for your work! Unfortunately we haven't achieved the requested 100% for coverage yet, see
https://circleci.com/gh/springfox/springfox/1703

Would you mind adding the necessary additional tests?

Html report: /home/ubuntu/springfox/springfox-bean-validators/build/reports/jacoco/test/html/index.html
------------------ Code Coverage Failed -----------------------
- instruction coverage rate is: 47.93%, minimum is 100%
- branch coverage rate is: 41.43%, minimum is 100%
- line coverage rate is: 49.05%, minimum is 100%
- complexity coverage rate is: 47.33%, minimum is 100%
- method coverage rate is: 52.08%, minimum is 100%

## \- class coverage rate is: 62.5%, minimum is 100%

:springfox-bean-validators:jacocoTestReport FAILED
:buildDashboard

FAILURE: Build failed with an exception.
- Where:
  Script '/home/ubuntu/springfox/gradle/coverage.gradle' line: 86
- What went wrong:
  Execution failed for task ':springfox-bean-validators:jacocoTestReport'.
  
  > Code coverage failed

**Comment by carlosjgp** [comment]
Glad to see that you like my test!
Really nice this Spock framework! :smile: 
I will create more tests soon! But you should improve the javadoc...

> instruction coverage rate is: 47.93%, minimum is 100%

Tests will cover the other ones :wink:

**Comment by jfiala** [comment]
> instruction coverage rate is: 47.93%, minimum is 100%

Yes, I'll deal with this let's get this done :)

**Comment by jfiala** [comment]
Cleaned up unnecessary code + Javadoc comments have been added to all methods where it makes sense...!

Result:
------------------ Code Coverage Failed -----------------------
- instruction coverage rate is: 58.26%, minimum is 100%
- branch coverage rate is: 51.85%, minimum is 100%
- line coverage rate is: 59.81%, minimum is 100%
- complexity coverage rate is: 54.87%, minimum is 100%
- method coverage rate is: 58.14%, minimum is 100%
- class coverage rate is: 62.5%, minimum is 100%

**Pull request merged**
